# Site settings
title: "Rails Dokümantasyonu - Türkçe"
description: "Ruby on Rails Kılavuzlarının Türkçe Çevirisi"
url: "https://dilankaya127.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Collections
collections:
  guides:
    output: true
    permalink: /:name/
    permalink: /guides/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "guides"
    values:
      layout: "guide"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

include:
  - rails
